# Generated by Django 4.1.7 on 2023-03-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Barbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('barber_surname', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('barber_phone', models.IntegerField(blank=True, default=None, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('barber_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.category')),
            ],
            options={
                'verbose_name': 'Барбер',
                'verbose_name_plural': 'Барбери',
            },
        ),
        migrations.CreateModel(
            name='BarberFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='barbers_foto')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbers.barbers')),
            ],
            options={
                'verbose_name': 'Фото барбера',
                'verbose_name_plural': 'Фото барберів',
            },
        ),
    ]
